name: igotyou
description: 纯记忆证明的兜底密码库
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ^3.13.0

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.0
  cryptography: ^2.9.0
  unorm_dart: ^0.3.2
  path_provider: ^2.1.0
  share_plus: ^13.3.0
  file_picker: ^12.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
